DJHSTAR Server Hosting/Controllers/DJHSTARController.cs
using DJHSTAR_Server_Hosting.Models;
using DJHSTAR_Server_Hosting.Services;
using System.Data.Entity;
using System.Linq;
using System.Windows.Forms;
using System.Web.Mvc;
//using Newtonsoft.Json;
//using BBC_RSS_Feed_Application.Models;

namespace DJHSTAR_Server_Hosting.Controllers
{
    public class DJHSTARController : Controller
    {
        private djhstarEntities db = new djhstarEntities();

        public ActionResult Index()
        {
           //List<Old_Status> model = new List<Old_Status>();
           //model = StatusCodes.GetAllStatusCodes();
            var events = db.events.Include(e => e.t_status).Where(e => e.t_status.resolved == false);
            return View(events);
           //return View(model);
        }

        public ActionResult ResolvedEvents()
        {
            var events = db.events.Include(e => e.t_status).Where(e => e.t_status.resolved == true);
            return View(events);
        }

        public ActionResult EventService()
        {
            DJHSTAR_Server_Hosting.Services.Host.StartEventService();
            return this.RedirectToAction("Index");
            //var events = db.events.Include(e => e.t_status);
            //return View(events);
        }
    }
}

DJHSTAR Server Hosting/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>


    
    <div class="navbar navbar-inverse navbar-fixed-top" style="max-height:50px;">
        <div style="position:relative; display:inline; float:left;" >
            <object data="~/Images/djhstarLogo3.svg" type="image/svg+xml" width="100" height="50"></object>
        </div>
        <div class="container">
            <div class="navbar-header" style="max-height:50px;">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DJHSTAR Server Hosting", "Index", "DJHSTAR", new { area = "" }, new { @class = "navbar-brand", @style = "position:relative"})
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "DJHSTAR")</li>
                    <li>@Html.ActionLink("Resolved Events", "ResolvedEvents", "DJHSTAR")</li>
                    <li>@Html.ActionLink("Status", "Index", "Status")</li>
                    <li>@Html.ActionLink("Events", "Index", "Events")</li>
                    <li>@Html.ActionLink("Comments", "Index", "Comments")</li>
                    <li>@Html.ActionLink("Fixes", "Index", "Fixes")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="float:left;">
                <text>&copy; @DateTime.Now.Year - My ASP.NET Application</text>
                <div style="position:relative; display:inline; float:left;">
                    @*<a href="http://djhstarserverhosting.azurewebsites.net/djhstar/EventService">*@
                    @*<a href="http://localhost:56578/djhstar/EventService">*@
                    @*<a href="/djhstar/EventService">*@
                        <object data="~/Images/feedIcon.png" type="image/png" width="14" height="14" style="margin:4px;"></object>
                    @*</a>*@
                </div>
                <div style="position:relative; display:inline; float:left;">
                    <a href="https://www.facebook.com/profile.php?id=664508197">
                        <object data="~/Images/facebookIcon.png" type="image/png" width="18" height="18" style="margin:0px;"></object>
                    </a>
                </div>
                <div style="position:relative; display:inline; float:left;">
                    <a href="https://twitter.com/djhstar">
                        <object data="~/Images/twitterIcon.jpg" type="image/jpg" width="18" height="18" style="margin:0px;"></object>
                    </a>
                </div>
            </p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>